### ISSUE TITLE
Implement inspect request

### ISSUE THREAD

**Issue by lassoan** [Slicer/SlicerJupyter#13]
Pressing Shift+Tab brings up the inspector window in the notebook, which shows documentation of the function where the cursor is at. Input code must be parsed to correctly identify the symbol that documentation should be displayed for.

Example:

Placing the cursor in getprofile shows its documentation (correctly ignores previous lines):

<img width="427" alt="image" src="https://user-images.githubusercontent.com/307929/44404645-56986100-a525-11e8-91d0-217ed9d5cb52.png">

Placing the cursor after getrecursionlimit's opening bracket, it shows documentation of getrecusrionlimit(correctly ignores getprofile symbol):

<img width="477" alt="image" src="https://user-images.githubusercontent.com/307929/44404780-a119dd80-a525-11e8-850e-5fa0af25f786.png">

This is the input that xeus receives:

```Received inspect_request
code: a=5
b=10
sys.getprofile(sys.getrecursionlimit()
cursor_pos: 24
detail_level: 0```

**Comment by lassoan** [comment]
@ihnorton @jcfr 

I've implemented inspection (printing documentation on Shift+Tab) using Jedi. It works for python classes, but Jedi seems to not be able to retrieve documentation for wrapped C++ classes. It may be an inherent limitation of Jedi, since it does not execute code.

To resolve this, we could generate python skeletons, similarly to how SimpleITK. PyCharm generates skeletons using [IntelliJ generator3](https://github.com/JetBrains/intellij-community/blob/master/python/helpers/generator3.py):

    PythonSlicer.exe "c:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\generator3.py" -d . MRMLCorePython c:\\D\\S4R\\Slicer-build\\bin\\Release\\MRMLCorePython.pyd

Skeleton would be nice because they would allow various Python IDEs to find method documentation.

Alternatively, we could change our approach and evaluate code - as the current Python terminal does it.

**Comment by ihnorton** [comment]
Neat! Quick note: `red = getNode("Red")` and then `red<Shift-Tab>` then it is able to show the docstring for `vtkMRMLColorTableNode`, but it doesn't work for `red.GetAddressAsString<Shift-Tab>`. So it can get some info for PyObjects defined in C++.

Do the IntelliJ skeletons include PEP484 type hints? That could let us use the static analysis features of Jedi/MyPy/Pyre (not really related to ipython, just potentially useful in general).

For now evaluating seems fine. No change to status quo, and no one is running a remote kernel server... (yet)

**Comment by lassoan** [comment]
> So it can get at least some info for PyObjects defined in C++.

Yes, it can get the class documentation but not method documentation. This is the same behavior as in PyCharm if you don't generate Python skeleton files for your wrapped C++ classes. It may be a limitation of Jedi.

**Comment by lassoan** [comment]
> Do the IntelliJ skeletons include PEP484 type hints? That could let us use the static analysis features of Jedi/MyPy/Pyre (not really related to ipython, just potentially useful in general).

There is some type information, but I'm not sure if they are PEP484 compatible. For example, skeletons for a get and a set method:

```
    def GetViewAngle(self): # real signature unknown; restored from __doc__
        """
        V.GetViewAngle() -> float
        C++: double GetViewAngle()
        
        Get the camera view angle
        \sa SetViewAngle(), vtkCamera::GetViewAngle(),
            GetParallelScale(),
        GetParallelProjection()
        """
        return 0.0

    def SetPosition(self, p_float=None, p_float=None_1, p_float=None_2): # real signature unknown; restored from __doc__
        """
        V.SetPosition([float, float, float])
        C++: void SetPosition(double position[3])
        V.SetPosition(float, float, float)
        C++: void SetPosition(double x, double y, double z)
        
        Set the position of the camera in world coordinates.
        \sa GetPosition(), SetFocalPoint(), SetViewUp()
        """
        pass
```

Maybe VTK's Python generator could be updated to generate PEP484 type hints?

**Comment by jcfr** [comment]
For reference: https://www.python.org/dev/peps/pep-0484/

> Maybe VTK's Python generator could be updated to generate PEP484 type hints?

@dgobbi What do you think ?

**Comment by dgobbi** [comment]
Do you know how this is applied to extension modules?  I did a quick scan of the PEP and all the examples were for pure Python code.

**Comment by dgobbi** [comment]
PEP484 is useless in terms of describing the implementation (since it only talks about syntax).  But after looking at Python's `funcobject.c` the implementation seems pretty straightforward.  It should be possible to add an `__attributes__` dict to `PyVTKMethodDescriptor.cxx` alongside the existing `__doc__` attribute.

**Comment by lassoan** [comment]
It sounds good, it'll be a great long-term solution. However, I'm not sure how widely various analysis tools can use __annotation__ field in binaries (and I think it is only supported for Python3, which will be a limitation for us for at least a couple of more months).

Would it be possible for VTK Python wrapper to generate Python skeletons (similar to those generated by [SWIG](http://swig.org/Doc3.0/Python.html#Python_nn67) or [IntelliJ generator3.py](https://github.com/JetBrains/intellij-community/tree/master/python/helpers)) or [stubs](https://www.python.org/dev/peps/pep-0484/#stub-files) (generated by [MyPy](https://mypy.readthedocs.io/en/stable/stubs.html#stub-files) or [make-stub-files](https://github.com/edreamleo/make-stub-files))? Many tools can provide auto-complete and documentation if these are available.

PyCharm can even get type hints from docstring (https://www.jetbrains.com/help/pycharm/using-docstrings-to-specify-types.html), which could be a simple short-term solution for Python2 for those who use PyCharm.

**Comment by dgobbi** [comment]
Could you post this as an issue on VTK's gitlab site?  That's where the related MRs will eventually go, so it seems best to have the conversation there.

I'm not fond of stubs, and generating the stubs would require an additional wrapping executable (and cmake rules to call it). Changing the docstrings would be easy, though. This is handled by the `vtkWrapText_PythonSignature()` method in the VTK wrappers, it would be very nice to modernize the signatures to include type information.

**Comment by lassoan** [comment]
Improved inspection to use docstring if definitions are not found by Jedi. With this, inspection works nicely.

![image](https://user-images.githubusercontent.com/307929/49832635-4111a600-fd65-11e8-85c4-1b2fe161b136.png)
