### ISSUE TITLE
Build docker image for Binder

### ISSUE THREAD

**Issue by lassoan** [Slicer/SlicerJupyter#15]
[Binder](https://mybinder.org/) can run Jupyter notebooks interactively using docker containers. All we would need to do is to [describe a docker container ](https://mybinder.readthedocs.io/en/latest/using.html#preparing-a-repository-for-binder) in the root of a repository that contains notebooks (see for example [this](https://github.com/lassoan/SlicerNotebooks))

**Comment by lassoan** [comment]
@ihnorton I know you have created docker containers for Slicer before. Would you be able to give it a try and put together a container that contains Slicer + SlicerJupyter extension?

**Comment by lassoan** [comment]
Binder could be useful for interactive demos, tests and scripting examples - even if we are limited to work with small data sets.

Could we use the same container on our own computers to work with larger data sets?

**Comment by jcfr** [comment]
> Could we use the same container on our own computers to work with larger data sets?

Yes. When started locally, the current folder (or folder of your choice would be mounted into the container), then you would be able to connect with your browser and work with larger dataset

**Comment by ihnorton** [comment]
Please see:

https://mybinder.org/v2/gh/ihnorton/SlicerNotebooks/master

- PR to add launch icon to notebook: https://github.com/lassoan/SlicerNotebooks/pull/1
- associated Dockerfile parent image: https://github.com/ihnorton/dockerfiles/tree/master/slicer2binder
  - currently has pinned binares checked-in with git-lfs because I compiled SlicerJupyter (w/ slicer nightly docker) and other hacks pending: https://github.com/Slicer/SlicerJupyter/issues/5

**Comment by lassoan** [comment]
This is awesome!!!

**Comment by lassoan** [comment]
@ihnorton Binder works very nicely! Would you be able to create a dockerfile with Slicer-4.10? Now I usually create notebooks with Slicer-4.10 kernel and it would be nice if the kernel in the dockerfile would be the same. Thank you!

**Comment by lassoan** [comment]
@jcfr Could you help updating binder (https://mybinder.org/v2/gh/slicer/SlicerNotebooks/master) to latest Preview Release? It would be awesome if people could try all the new features right away, without installing Slicer, Anaconda, and configuring jupyter kernel.

**Comment by jcfr** [comment]
Will have a look later tonight when back home.

**Comment by lassoan** [comment]
Thanks a lot! I'll wait for you with the announcement then (in the meantime I'll create a demo video).

**Comment by lassoan** [comment]
Done, everything works well. See https://github.com/Slicer/SlicerDocker and https://mybinder.org/v2/gh/slicer/SlicerNotebooks/master
