### ISSUE TITLE
Binder improvement ideas

### ISSUE THREAD

**Issue by ihnorton** [Slicer/SlicerJupyter#17]
Issue to collect ideas/notes for SlicerJupyter+binder.

Easy:

- [ ] set up automatic update of the docker image, after https://github.com/Slicer/SlicerJupyter/issues/5
- [ ] make the Slicer window full-screen in the virtual X window. Right now the images captured by `display()` reflect the size of the running virtual display, which is about 1/4 of the 1280x1024 screen, so they are usually much smaller than the saved image when a notebook is re-run. The “awesome” window manager I'm using can be controlled with Lua, so if this can’t be done directly in Slicer/Qt, then it could be applied to the window in a launcher script.
- clean up slicer2binder Dockerfile
  - move the Slicer dependencies to a separate docker stage
  - move Dockerfile to Slicer org, maybe de-dup with Steve's and Matt's
- make virtual X display size configurable, right now it is kind of hard-coded in xorg.conf

Maybe easy:
- [ ] add VNC access - see https://github.com/yuvipanda/jupyter-desktop-server for an example

Hard:
- [ ] make kernel start faster! Obviously this is a big/general issue. It's one reason I initially started trying to [build against musl libc](https://github.com/ihnorton/dockerfiles/tree/master/alpine-slicer), but ran in to various problems - mostly with Python and VTK (ITK does build against musl). Not sure if @cpinter had any luck with the static build, but that might help.

Speculative:

- hide the slider handles in screenshots, could be confusing to users. Not sure if that's possible in Qt.

**Comment by lassoan** [comment]
Maybe others have higher expectations, but for me startup time is perfectly fine.

You can hide the sliders - see one of the examples in SlicerNotebooks notebook 01. Should we do hide them when calling `display()`?

**Comment by lassoan** [comment]
I would add that sometimes it would be useful to have GUI access. Would it be possible to offer a VNC connection?

**Comment by lassoan** [comment]
> hide the slider handles in screenshots, could be confusing to user

done!

**Comment by lassoan** [comment]
> make the Slicer window full-screen in the virtual X window

Window can be maximized using Python by calling `slicer.util.mainWindow().showMaximized()`

**Comment by lassoan** [comment]
All features except automatic image updates have been implemented. We'll see how well manual updates work.
