### ISSUE TITLE
Update CryptoPP

### ISSUE THREAD

**Issue by jcfr** [Slicer/SlicerJupyter#19]
Current version is from August 6 2018, see https://github.com/weidai11/cryptopp/commit/2ec9c9963c6ca58e8c764cc64b28fdb52eca28d7 and https://github.com/Slicer/SlicerJupyter/blob/18f1346d735126196cda52ee015c864b88f7b962/SuperBuild/External_cryptopp.cmake#L21-L32

See https://github.com/QuantStack/xeus/pull/103#issuecomment-443692180

**Comment by SylvainCorlay** [comment]
Note, this should not be an issue anymore if you upgrade to the latest version of `xeus` as we dropped cryptopp and adopted OpenSSL for signing messages.

**Comment by jcfr** [comment]
Thanks for the heads up :pray: 

This is great as we already build OpenSSL as part of Slicer core.

**Comment by jcfr** [comment]
Closing. This is obsoleted by #36 and #30
