### ISSUE TITLE
Automate installation of kernel file

### ISSUE THREAD

**Issue by jcfr** [Slicer/SlicerJupyter#2]
Instead of asking the user to explicitly call `jupyter-kernelspec install`, we should ask the user to select a python installation.

The Slicer module would then take care of:
* creating a virtual environment (using `venv` for regular python, and `conda env` for anaconda ...)
* installing `jupyter`
* installing the Slicer kernel

Slicer kernel  should be named using a convention like this one: `Slicer X.Y.Z[-YYYY-MM-DD-rNNNN]`

Build tree and install tree should be supported

**Comment by lassoan** [comment]
I've implemented automated install of the Slicer kernel in JupyterKernel module. You just need to select Python Scripts folder.

I've chosen to set the kernel identifier to be Slicer X.Y, as this way when somebody starts a notebook, there is a good chance that a matching kernel is found. Kernel display name can be a more specific version, if we find that it is useful.

**Comment by SylvainCorlay** [comment]
Check out how we install kernel specs for the C++ kernel based on xeus

https://github.com/QuantStack/xeus-cling/

Basically, the kernel spec files are configured and installed by CMake (upon cmake install) without using Python, assuming that the jupyter installation is in the same prefix.

You can also set a `XEXTRA_JUPYTER_DATA_DIR` to install the spec in another location.

**Comment by lassoan** [comment]
Thanks for the information Sylvain. It sounds like a nice approach for cases when users build the kernel on their computer.

In case of Slicer, most users would not be comfortable setting up build environment for Slicer and do not even have CMake installed. We precompile all extensions (such as SlicerJupyter) and distribute the binaries on [Slicer appstore](http://slicer.kitware.com/midas3/slicerappstore?os=win&arch=amd64&revision=27269&category=Developer%20Tools&search=&layout=layout) so that they can install them by a few clicks.

**Comment by SylvainCorlay** [comment]
It makes sense. For the distribution of the built package, we make use of the conda package manager, which handles relocation by replacing hard coded prefix paths in all files of the package.

I imagine that this would be a good approach if you package slicer and extensions for conda, apt-get or other package managers.

**Comment by SylvainCorlay** [comment]
In any case, it is probably a good thing that when installing a kernel in a prefix, the kernel adds its kernel spec in the `share/jupyter/` directory for that prefix.

**Comment by lassoan** [comment]
Installation of kernelspec works OK, by clicking "Install Slicer kernel in Jupyter" in JupyterKernel module.
