### ISSUE TITLE
SlicerJupyter extension not availble on Slicer 4.10.1 on Linux based distribution

### ISSUE THREAD

**Issue by che85** [Slicer/SlicerJupyter#20]
@lassoan We set up the Deep Learning with RHEL, and I downloaded Slicer version 4.10.1

I noticed that there is no SlicerJupyter extension available from the Extension Manager. 

Can you take a look at that, if you find the time?

cc: @mattjolley

**Comment by mattjolley** [comment]
@lassoan @jcfr 

For Deep Learning on Linux is really much easier than Windows.

CHOP dictates what linux version we use (RHEL).

Having the option to run SlicerJupyter would be really helpful for us as we can do data transformations and interact with the data.

Let us know what our options are for this...

**Comment by lassoan** [comment]
Probably it's some trivial issue (http://slicer.cdash.org/viewBuildError.php?buildid=1494675 indicates there is some variably type casting problem). If you have a Linux system where you have built Slicer, fixing this build error should not be difficult.

@che85 Could you have a look? If it is not trivial then call me on Skype and we can have a look at it together.

**Comment by che85** [comment]
I don't have a Linux build of Slicer and I don't have much experience with RHEL. Does anyone of you have a Linux machine for quickly testing this? It's not urgent but would be nice to have. 

If that's not the case, I can try to build it sometime.

**Comment by lassoan** [comment]
> I can try to build it sometime.

I see. I thought that it has been already set up.

If we want to SlicerHeart on Linux then we'll also need to set up a Slicer build at least one of those Linux boxes. I'll set up a Linux VM on my computer, too.

**Comment by jcfr** [comment]
As a side note, the linux build and extension could be done using the same docker image `slicer/buildenv-qt5-centos7:latest` that we use on the factory. For more details, see https://github.com/Slicer/SlicerBuildEnvironment

for reference, corresponding dashboard script is: https://github.com/Slicer/DashboardScripts/blob/master/metroplex.sh

I will have a look at the issue.

**Comment by mattjolley** [comment]
Basically it is helpful to do some pre-processing and data output using the Slicer environment.

We have a physical machine for Deep Learning setup to do this, but it is not a good machine to do general testing on as we are using it for Deep Learning production.

We can see if they will give us a RHEL VM to do testing on, but if you guys have a good setup to do it you are FAR more familiar with debugging builds of Slicer than we are.

**Comment by mattjolley** [comment]
Thank You @JCFR.

We will take a look tomorrow!

**Comment by che85** [comment]
SlicerJupyter extension is now available in ExtensionManager, but after installation and restart of Slicer 
I am getting an error that can be fixed by moving files into the right directory. See below.

```
Cannot load library /home/herzc/.config/NA-MIC/Extensions-27931/SlicerJupyter/lib/libqSlicerJupyterKernelModule.so: (libxeus.so.1: cannot open shared object file: No such file or directory)
```
![image](https://user-images.githubusercontent.com/10195822/51687316-4008a100-1fc0-11e9-9642-f63b0fb8a564.png)

The missing files are located in `/home/herzc/.config/NA-MIC/Extensions-27931/SlicerJupyter/lib/`

![image](https://user-images.githubusercontent.com/10195822/51687281-34b57580-1fc0-11e9-918c-24cc4b2c49ab.png)


The error disappears after manually moving them into `/home/herzc/.config/NA-MIC/Extensions-27931/SlicerJupyter/lib/Slicer-4.10/qt-loadable-modules`

![image](https://user-images.githubusercontent.com/10195822/51687559-c91fd800-1fc0-11e9-82a8-7229c18a523c.png)

**Comment by mattjolley** [comment]
Thank you guys for working on this...

**Comment by lassoan** [comment]
@che85 The commit above should fix the issues. It would be great if you could test this on tomorrow's Slicer build.

**Comment by jfaurelacroix** [comment]
Hi, 
jumping in on this to confirm that the extension works but the kernel keeps restarting after switching to module "Welcome". A window will quickly appear and disappear and the kernel dies.

**Comment by lassoan** [comment]
Closing this, assuming the referenced commit fixed the issue. Open a new issue if there are still problems.
