### ISSUE TITLE
Kernel gets installed but does not shows up in the jupyter notebook

### ISSUE THREAD

**Issue by sedghi** [Slicer/SlicerJupyter#23]
I can successfully install the kernel after running 
`jupyter-kernelspec install /home/username/.config/NA-MIC/Extensions-27968/SlicerJupyter/share/Slicer-4.11/qt-loadable-modules/JupyterKernel/Slicer-4.11/ --replace --user`
and I get the `[InstallKernelSpec] Installed kernelspec slicer-4.11 in /home/username/.local/share/jupyter/kernels/slicer-4.11` message indicating my kernel installation is sucessful. 

However, when I run the jupyter notebook I don't see the kernel, and when I run `jupyter kernelspec list` I don't see the kernel there neither. 

I'm using Ubuntu 16.04 and Slicer 4.11.0-2019-02-19 r27968, and anaconda virtual environment

**Comment by sedghi** [comment]
Update: the automatic installation with inside Slicer works, but the developer installation guide does not

**Comment by jcfr** [comment]
After installing from Slicer, does running `jupyter kernelspec list` in the corresponding environment lists the kernel ?

**Comment by sedghi** [comment]
Thanks for the reply,
Yes it will show up after installing inside Slicer and it works well although not having the auto-complete capability

**Comment by lassoan** [comment]
Closing this now.

Separate issue is added for auto-complete not working on Slicer-4.11 - https://github.com/Slicer/SlicerJupyter/issues/27.
