### ISSUE TITLE
SlicerJupyter documentation on functions. 

### ISSUE THREAD

**Issue by garbulinskamaja** [Slicer/SlicerJupyter#25]
Hi! I would like to use SlicerJupyter to display images from jupyter notebook, have them labeled in the editor in Slicer and save the mask as .tiff also using commands from python. 

I cannot seem to find documentation on what functions I should use to have it work.  

Thanks

**Comment by lassoan** [comment]
Do you segment a 2D image or a 3D volume?

You can find many examples of saving/loading/manipulating segmentations in Python in the [script repository](https://www.slicer.org/wiki/Documentation/Nightly/ScriptRepository#Segmentations).

**Comment by garbulinskamaja** [comment]
Thanks! Our goal is to do both 3D and 2D.

**Comment by lassoan** [comment]
You can access voxels of a volume as a numpy array using `slicer.util.arrayFromVolume` and then slice it and write it to any image file format. You can also use VTK and SimpleITK functions to slice volumes and write to file.

**Comment by lassoan** [comment]
You can now also use `display(filename='MatplotlibExample.png', type="image/png", binary=True)` to display an image as a result of a cell execution.
