### ISSUE TITLE
nightly version cant install packages

### ISSUE THREAD

**Issue by garbulinskamaja** [Slicer/SlicerJupyter#26]
Hi! We are trying to integrate slicer and pytorch and some other packages. There is no way we can get PyTorch or any other package to install through the interpreter. Interestingly, the interpreter tells me that slicer runs in my base environment where I do have the packages I need, but it fails to import them. 

We have installed the nightly version because we need python 3, but when trying to do. 

`import pip

pip.main(['install', 'scipy']) `

We get "AttributeError: module 'pip' has no attribute 'main'". 

Could anyone help?

**Comment by garbulinskamaja** [comment]
wrong forum

**Comment by lassoan** [comment]
`pip.main` is not supported in Python3. You can use `pip_install("something")` in Slicer's Python console (for any operations that don't require updates of any packages that are already loaded), or run `PythonSlicer -m pip install something` from the command line.
