### ISSUE TITLE
Slicer kernel cannot start

### ISSUE THREAD

**Issue by tayebzaidi** [Slicer/SlicerJupyter#29]
After installing the 4.10 Slicer kernel successfully (as indicated by the text within the JupyterKernel extension), I tried to select the kernel in jupyter.
It begins to start, and then gives me this error message:

```
Jupyter connection file: [/home/emclab/.local/share/jupyter/runtime/kernel-5c44bbb4-9b6a-4bf7-9861-bcc42feaa7eb.json]
error: [/home/emclab/Downloads/InstalledSoftware/Slicer/bin/SlicerApp-real] exit abnormally - Report the problem. 
```

Investigating a little bit, I was also unable to run SlicerApp-real directly when navigating to it from a terminal.  It does not start and exits with the error message:
`./SlicerApp-real: error while loading shared libraries: libqSlicerApp.so: cannot open shared object file: No such file or directory`

I'm not sure that that test means anything because I suspect I'm not meant to run SlicerApp-real directly from a command line.  I am using the stable binary release downloaded off of the Slicer website today

In any case there is an error with the kernel setup and I cannot run a jupyter notebook using the Slicer kernel.

**Comment by lassoan** [comment]
Can you start Slicer using the launcher (./Slicer in the root of the install tree)?

**Comment by tayebzaidi** [comment]
Yes, Slicer itself works without issues

**Comment by lassoan** [comment]
Could you try with a recent Slicer Preview Release (Slicer-4.11.x)?
Can you get a stack trace of the crash?

**Comment by tayebzaidi** [comment]
I have tried now with Slicer-4.11 and the same error occurs.  

Here is the result that displays when analyzing the coredump file in gdb and running backtrace:
`Reading symbols from /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/SlicerApp-real...
(No debugging symbols found in /home/emclab/Downloads/InstalledSoftware/Sli--Type <RET> for more, q to quit, c to continue without paging--c
cer-4.11.0-2019-10-29-linux-amd64/bin/SlicerApp-real)
[New LWP 15987]
[New LWP 15996]
[New LWP 15993]
[New LWP 16001]
[New LWP 15991]
[New LWP 16003]
[New LWP 16002]
[New LWP 16004]
[New LWP 16054]
[New LWP 16057]
[New LWP 16053]
[New LWP 16071]
[New LWP 16063]
[New LWP 15998]
[New LWP 15999]
[New LWP 16061]
[New LWP 16051]
[New LWP 15989]
[New LWP 16062]
[New LWP 16000]
[New LWP 16059]
[New LWP 15992]
[New LWP 16058]
[New LWP 16070]
[New LWP 16068]
[New LWP 15988]
[New LWP 16052]
[New LWP 15994]
[New LWP 15995]
[New LWP 16060]
[New LWP 16067]
[New LWP 16069]
[New LWP 15997]
[New LWP 16072]
[New LWP 15990]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/b'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007f0b4ce3c075 in nlohmann::detail::serializer<nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> >::dump_escaped(std::string const&, bool) [clone .constprop.155] () from /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/libxeus.so.1
[Current thread is 1 (Thread 0x7f0c4559a480 (LWP 15987))]
(gdb) backtrace
#0  0x00007f0b4ce3c075 in nlohmann::detail::serializer<nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> >::dump_escaped(std::string const&, bool) [clone .constprop.155] ()
    at /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/libxeus.so.1
#1  0x00007f0b4ce30bdf in nlohmann::detail::serializer<nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> >::dump(nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> const&, bool, bool, unsigned int, unsigned int) [clone .constprop.154] ()
    at /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/libxeus.so.1
#2  0x00007f0b4ce3015d in nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>::dump(int, char, bool) const [clone .constprop.150] ()
    at /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/libxeus.so.1
--Type <RET> for more, q to quit, c to continue without paging--c
#3  0x00007f0b4ce28a55 in xeus::write_zmq_message(nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> const&) () at /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/libxeus.so.1
#4  0x00007f0b4ce3aae9 in xeus::xmessage_base::serialize(zmq::multipart_t&, xeus::xauthentication const&) && () at /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/libxeus.so.1
#5  0x00007f0b4ce2d44f in xeus::xpub_message::serialize(zmq::multipart_t&, xeus::xauthentication const&) && () at /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/libxeus.so.1
#6  0x00007f0b4ce26ea7 in xeus::build_start_msg(std::unique_ptr<xeus::xauthentication, std::default_delete<xeus::xauthentication> >&, std::string const&, std::string const&, std::string const&, zmq::multipart_t&) () at /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/libxeus.so.1
#7  0x00007f0b4ce29fb1 in xeus::xkernel::start() () at /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/libxeus.so.1
#8  0x00007f0b4d3961ea in qSlicerJupyterKernelModule::startKernel(QString const&) () at /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/qt-loadable-modules/libqSlicerJupyterKernelModule.so
#9  0x00007f0b4d39c829 in qSlicerJupyterKernelModule::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () at /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/qt-loadable-modules/libqSlicerJupyterKernelModule.so
#10 0x00007f0b4d39c928 in qSlicerJupyterKernelModule::qt_metacall(QMetaObject::Call, int, void**) () at /home/emclab/.config/NA-MIC/Extensions-28573/SlicerJupyter/lib/Slicer-4.11/qt-loadable-modules/libqSlicerJupyterKernelModule.so
#11 0x00007f0c6387b49f in PythonQtCallSlot(PythonQtClassInfo*, QObject*, _object*, bool, PythonQtSlotInfo*, void*, _object**, void**, PythonQtPassThisOwnershipType*) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libPythonQt.so
#12 0x00007f0c6387dfc6 in PythonQtSlotFunction_CallImpl(PythonQtClassInfo*, QObject*, PythonQtSlotInfo*, _object*, _object*, void*, void**, PythonQtPassThisOwnershipType*) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libPythonQt.so
#13 0x00007f0c6387ef28 in PythonQtMemberFunction_Call(PythonQtSlotInfo*, _object*, _object*, _object*) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libPythonQt.so
#14 0x00007f0c5f2f2bba in _PyObject_FastCallDict () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Python/lib/libpython3.6m.so
#15 0x00007f0c5f3c721b in  () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Python/lib/libpython3.6m.so
#16 0x00007f0c5f3caf7d in _PyEval_EvalFrameDefault () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Python/lib/libpython3.6m.so
#17 0x00007f0c5f3c70cd in  () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Python/lib/libpython3.6m.so
#18 0x00007f0c5f3c768e in PyEval_EvalCodeEx () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Python/lib/libpython3.6m.so
#19 0x00007f0c5f3c76bb in PyEval_EvalCode () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Python/lib/libpython3.6m.so
#20 0x00007f0c5f41569f in PyRun_StringFlags () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Python/lib/libpython3.6m.so
#21 0x00007f0c637de44a in PythonQt::evalScript(_object*, QString const&, int) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libPythonQt.so
#22 0x00007f0c6387891f in PythonQtObjectPtr::evalScript(QString const&, int) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libPythonQt.so
#23 0x00007f0c647d89ad in ctkAbstractPythonManager::executeString(QString const&, ctkAbstractPythonManager::ExecuteStringMode) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libCTKScriptingPythonCore.so.0.1
#24 0x00007f0c706ca348 in qSlicerCoreApplication::handleCommandLineArguments() () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libqSlicerBaseQTCore.so
#25 0x00007f0c71f28349 in qSlicerApplication::handleCommandLineArguments() () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libqSlicerBaseQTGUI.so
#26 0x00007f0c70721d29 in  () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libqSlicerBaseQTCore.so
#27 0x00007f0c5a45e0e1 in QObject::event(QEvent*) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5Core.so.5
#28 0x00007f0c5aa5b3b4 in QGuiApplication::event(QEvent*) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5Gui.so.5
#29 0x00007f0c5b289608 in QApplication::event(QEvent*) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5Widgets.so.5
#30 0x00007f0c5b283e2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5Widgets.so.5
#31 0x00007f0c5b28af60 in QApplication::notify(QObject*, QEvent*) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5Widgets.so.5
#32 0x00007f0c71f27f3c in qSlicerApplication::notify(QObject*, QEvent*) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libqSlicerBaseQTGUI.so
#33 0x00007f0c5a4322d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5Core.so.5
#34 0x00007f0c5a434ceb in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5Core.so.5
#35 0x00007f0c5a486d93 in  () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5Core.so.5
#36 0x00007f0c491de84d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007f0c491dead0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007f0c491deb73 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007f0c5a4863ff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5Core.so.5
#40 0x00007f0c44b050d1 in  () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5XcbQpa.so.5
#41 0x00007f0c5a430c3a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5Core.so.5
#42 0x00007f0c5a439640 in QCoreApplication::exec() () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libQt5Core.so.5
#43 0x00007f0c706c554a in qSlicerCoreApplication::exec() () at /home/emclab/Downloads/InstalledSoftware/Slicer-4.11.0-2019-10-29-linux-amd64/bin/../lib/Slicer-4.11/libqSlicerBaseQTCore.so
#44 0x0000000000404df0 in main ()`

 I haven't read stack traces before myself, so let me know if this is what you're looking for.

**Comment by tayebzaidi** [comment]
An update:  I tried to run this in a docker container with Ubuntu 18.04, using the slicer2binder dockerfile as a guide.  I was able to get Slicer functioning and installed the extension however SlicerJupyter still failed when trying to start the kernel.  I wasn't able to get a stack trace there but the initial error message was identical.

**Comment by lassoan** [comment]
SlicerJupyter works fine on binder. Could you try if that works without modifications, and if it works then make changes step-by-step to see what breaks it?

**Comment by lassoan** [comment]
On linux there are often issues around OpenSSL, see for example this proposed fix in a recent pull request: https://github.com/Slicer/Slicer/pull/1260

**Comment by lassoan** [comment]
It should work fine now with recent Slicer-4.11 versions. Reopen this issue if you still experience problems.

**Comment by bveeni** [comment]
Hi,
I am facing this issue of "unable to start kernel for slicer".
Jupyter connection file: [/home/emclab/.local/share/jupyter/runtime/kernel-5c44bbb4-9b6a-4bf7-9861-bcc42feaa7eb.json]
error: [/home/emclab/Downloads/InstalledSoftware/Slicer/bin/SlicerApp-real] exit abnormally - Report the problem.
The version of slicer is 4.13.
I am running docker image on my VM and facing this issue there
using
docker run -p 8888:8888 -p49053:49053 -v "$PWD":/home/sliceruser/work --rm -ti lassoan/slicer-notebook:2021-10-15-b3077c2
However, this works fine on my local maching, just not working on my VM.
Thanks

**Comment by lassoan** [comment]
This issue is closed. Please open a new issue for discussing your problem. Thank you!
