### ISSUE TITLE
Update to use xeus-python

### ISSUE THREAD

**Issue by SylvainCorlay** [Slicer/SlicerJupyter#30]
It may be interesting to update to the latest xeus and use xeus-python for the `SlicerJupyter` kernel. 

- This should bring richer tracebacks, widget support, rich mime type rendering.
- This would remove the need for `cryptopp` for signing messages as we now use `OpenSSL`  which is already a dependency of Slicer.
- The xeus project, together with xeus-python and xeus-cling are moving under the Jupyter governance to their own organization. The JEP for incorporation was merged a couple of days ago.
- xeus-python implements now the debug adaptor protocol and is the current backend to the JupyterLab visual debugger: https://github.com/jupyterlab/debugger.

**Comment by SylvainCorlay** [comment]
Wait, did you guys switch to xeus-python?

**Comment by lassoan** [comment]
Not using xeus-python yet. The issue seems to have been auto-closed because it was mentioned in the pull request. I'll give it a go.

**Comment by lassoan** [comment]
@SylvainCorlay I've managed to make Slicer work with the xeus-python kernel and it is awesome! See https://github.com/Slicer/SlicerJupyter/pull/38.

![2020-05-02_14-02-05](https://user-images.githubusercontent.com/307929/80872139-30294380-8c7e-11ea-8420-fe6d5a500756.gif)

It was hard to explain to people why they cannot use widgets and why many convenience features are missing from Slicer notebooks - we'll soon get rid of all these limitations. There are still a few open issues (mostly replacing previous Slicer-specific workarounds with proper implementations), but we should be able to complete the switch soon!

Thank you very much for your hard work and developing these superb libraries. We could not achieve what we have now without them.

**Comment by SylvainCorlay** [comment]
> Thank you very much for your hard work and developing these superb libraries. We could not achieve what we have now without them.

We owe a lot of this to @martinRenou who worked hard on the widgets support in xeus-python.

The next steps in xeus-python are the support of IPython magics and the inline matplotlib backend...
