### ISSUE TITLE
Slicer 4.10 unable to maintain connection to kernel

### ISSUE THREAD

**Issue by themantalope** [Slicer/SlicerJupyter#31]
I am attempting to run slicer and Jupyter on my own machine. I installed SlicerJupyter as instructed 
and installed the kernel per the instructions and by copying the command supplied by the SlicerJupyter module.

I am able to select the Slicer kernel as expected for a new notebook.

As the notebook loads, Slicer is started (as expected), however after about 10 seconds the notebook loses connection to the kernel, slicer shuts down and then Jupyter attempts to re-connect which re-launches slicer, and the process fails again.

The only output in the terminal that I get (where I am running `jupyter notebook` from) is below:

```bash
Switch to module:  "Welcome"
starting storescp process
(u'Starting /opt/Slicer/bin/../bin/storescp with ', ['11112', '--accept-all', '--output-directory', u'/home/matt/Documents/SlicerDICOMDatabase/incoming', '--exec-sync', '--exec-on-reception', u'/opt/Slicer/bin/../bin/dcmdump --load-short --print-short --print-filename --search PatientName "/home/matt/Documents/SlicerDICOMDatabase/incoming/#f"'])
process /opt/Slicer/bin/../bin/storescp now in state Starting
process /opt/Slicer/bin/../bin/storescp now in state Running
Jupyter connection file: [/home/matt/.local/share/jupyter/runtime/kernel-d8fe4d3d-7538-4a65-8d45-366fb853a0a4.json]
[W 15:47:56.001 NotebookApp] Replacing stale connection: d8fe4d3d-7538-4a65-8d45-366fb853a0a4:e02dc0d014cf4a278ff809dd32662747
```

Please let me know if I am missing something, or if I should install any software differently

**Comment by lassoan** [comment]
It seems that your kernel launch timeout is set to a very small value (10 seconds) and Slicer cannot start on your computer within this short time. Increasing KERNEL_LAUNCH_TIMEOUT should fix the issue.

**Comment by themantalope** [comment]
Is this an environment variable?

**Comment by lassoan** [comment]
I'm not sure, I've found this as an answer for similar questions about kernels that are slow to start. It is either an environment variable or in a Jupyter configuration file. Let me know what you have found out.

**Comment by themantalope** [comment]
I tried both setting this as an environment variable and looking in the generated jupyter_config.py file. Nothing really seemed to work. Do you know where you saw that as an answer? Have you ever run into this issue where the kernel shuts down after giving a "stale connection" error message?

**Comment by lassoan** [comment]
What Python distribution do you use? Can you try a clean Python3 64-bit Anaconda install? That worked fine for me.

**Comment by lassoan** [comment]
Replaced custom Python kernel by xeus-python. Tested on Windows and in slicer-notebook docker (https://github.com/Slicer/SlicerDocker).
