### ISSUE TITLE
Test integration with itkwidgets

### ISSUE THREAD

**Issue by lassoan** [Slicer/SlicerJupyter#43]
Try how https://github.com/InsightSoftwareConsortium/itkwidgets can be used in Slicer's environment. They could be very useful for quick client-side visualization.

**Comment by lassoan** [comment]
There seems to be packaging issues (see https://github.com/Slicer/SlicerJupyter/pull/38#issuecomment-624966705).

@thewtex could you please let us know when the problem is fixed and we can start testing itkwidgets? Is there an earlier version that we can pip install?

**Comment by thewtex** [comment]
@lassoan yes, will let you know, working on the install issue.

You can try 0.26.1 in the meantime.

**Comment by lassoan** [comment]
Thank you! I've tried itkwidgets==0.26.1 and have the same issue (viewer does not appear) in 3DImage.ipynb. 

Same with xeus-python and with a standard ipython kernel.
Windows10, Python version: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

**Comment by thewtex** [comment]
> Windows10, Python version: 3.7.6 (default, Jan 8 2020, 20:23:39)

I just tried with this setup, and both 0.26.1 and 0.27.2 worked for me. Here were the steps:

```
# Open Command Prompt
cd C:\
C:\Python37-x64\python.exe -m venv ./venv
cd venv
# Forgot 0.26.1 the first time, 0.27.2 also works locally, I am fixing it for Binder
.\Scripts\python.exe -m pip install itkwidgets==0.26.1
# Download 3DImage.ipynb to the current directory
.\Scripts\jupyter.exe notebook 3DImage.ipynb
```

Does this work on your system? What is different about the setup? Thanks in advance, Andras.

**Comment by lassoan** [comment]
Still does not work:

![image](https://user-images.githubusercontent.com/307929/81353580-6c520f00-9097-11ea-95ac-52b8fef5fd6b.png)

![image](https://user-images.githubusercontent.com/307929/81353590-7247f000-9097-11ea-8803-2b97012e75d5.png)

I used anaconda navigator to create a new Python-3.7 environment, installed jupyter notebook, and entered the cells shown in the screenshots above. Does this help? Do you have any clue about what could go wrong?

**Comment by lassoan** [comment]
I've installed the itkwidgets 0.26.1 for both the kernel and notebook sides and restarted my computer and it works now! Thanks for your help.

**Comment by lassoan** [comment]
@thewtex I'm looking at the [documentation](https://github.com/InsightSoftwareConsortium/itkwidgets/blob/master/itkwidgets/widget_viewer.py#L582-L729) of the viewer and I'm trying to find where to set volume rendering transfer functions. I see that gradient opacity transfer function can be set directly using gradient_opacity, custom color transfer function can be probably hacked into _custom_cmap, but I can't find where to set a scalar opacity transfer function. Can you advise?

**Comment by thewtex** [comment]
@lassoan the transfer functions can currently only be set via the user interface. We could also add traits to set / get them -- I created an issue to track this here: https://github.com/InsightSoftwareConsortium/itkwidgets/issues/304. We are currently bringing in support for multi-component volumes and label maps, and we will wait until that is in place first (each component has its own transfer function).

**Comment by lassoan** [comment]
itkwidgets are confirmed to work. However, there are some limitations/issues with displaying models larger than a few 100k points, volume rendering cannot be configured yet to properly render medical images, etc.

Since dynamic Slicer views are quite capable (rendering of all 2D and 3D content - multiple images, segmentations, markups, models, regions, transformed volumes, volume rendering, ...), we won't configure display hook to use itkwidgets for rendering MRML nodes in the notebook. However, we'll keep this in mind and revisit later, when more features are added to itkwidgets and/or important use cases emerge that require client-side rendering instead of server-side remote rendering.
