### ISSUE TITLE
SlicerWeb.ipynb error 404

### ISSUE THREAD

**Issue by tashrifbillah** [Slicer/SlicerJupyter#46]
Clicked on `launch | binder` badge.

![image](https://user-images.githubusercontent.com/35086881/84309217-cc702100-ab2d-11ea-8bce-18c883252d62.png)

**Comment by lassoan** [comment]
Note that the current image used for Slicer Jupyter notebooks is available here:
https://github.com/Slicer/SlicerDocker/
