### ISSUE TITLE
Many features missing in Jupyter terminal 

### ISSUE THREAD

**Issue by tashrifbillah** [Slicer/SlicerJupyter#48]
I opened a terminal as follows:

![image](https://user-images.githubusercontent.com/35086881/84413607-df8ef980-abde-11ea-8a4e-a5cdb3bc6a12.png)

On the terminal, the following features are missing:
* tab completion
* arrows
* navigation by home/end keys

As you may realize-- I have to type every single folder name to be able to move around on this terminal which is really difficult.

**Comment by lassoan** [comment]
What do you use the terminal for?

**Comment by tashrifbillah** [comment]
Testing some extensions with Slicer Notebook.

**Comment by lassoan** [comment]
I see. You can start a bash shell by typing `bash`. After that, tab completion works.

We could probably set the default shell to bash somewhere in the docker image. Something similar to what was recommended here: https://github.com/jupyterlab/jupyterlab/issues/2779#issuecomment-501616582

Could you give it a try to change the default shell in the [slicer-notebook dockerfile](https://github.com/Slicer/SlicerDocker/blob/master/slicer-notebook/Dockerfile)?

**Comment by tashrifbillah** [comment]
With `bash` all the missing features are restored 👍
