### ISSUE TITLE
CTACardio data download failed

### ISSUE THREAD

**Issue by tashrifbillah** [Slicer/SlicerJupyter#50]
![image](https://user-images.githubusercontent.com/35086881/84510926-c72ce680-ac93-11ea-8ec9-2b338b51709d.png)

Note: This issue is independent of #49.

**Comment by tashrifbillah** [comment]
Same issue with `SampleData.SampleDataLogic().downloadAbdominalCTVolume()`

**Comment by lassoan** [comment]
This works well in official builds and in binder, too:

![image](https://user-images.githubusercontent.com/307929/84615879-2ce9c000-ae98-11ea-859e-657f82bfb182.png)

Maybe you have built Qt without SSL support? Then you may not be able to download data from https sites.

**Comment by tashrifbillah** [comment]
> Then you may not be able to download data from https sites.

Can you name another such data for downloading and comparing against this issue?

**Comment by lassoan** [comment]
It is hard to find http sites nowadays but for example this link used to work:

http://wiki.slicer.org/slicerWiki/images/2/2a/CarreraSliceEffect.png

(if I open this in a web browser then of course it is redirected to https, so I cannot tell for sure that it is still available with http)
