### ISSUE TITLE
module 'JupyterNotebooksLib' has no attribute 'AppWindow'

### ISSUE THREAD

**Issue by tashrifbillah** [Slicer/SlicerJupyter#51]
Tried this cell on a local kernel:

![image](https://user-images.githubusercontent.com/35086881/86494993-67cb6f00-bd45-11ea-8926-bc0d539d95df.png)

---

Ran into this error:

![image](https://user-images.githubusercontent.com/35086881/86495013-8467a700-bd45-11ea-9f4a-4036db7ba943.png)

**Comment by lassoan** [comment]
You need to install ipywidgets in both Slicer's Python environment and the external Python environment as described in the installation instructions (https://github.com/Slicer/SlicerJupyter#option-3-install-slicer-and-jupyter-on-your-own-computer).
