### ISSUE TITLE
Slicer 4.11 freezes when evaluating an expression of type vtkMRMLModelNode

### ISSUE THREAD

**Issue by fusentasticus** [Slicer/SlicerJupyter#54]
I make a new notebook, connect it to the 4.11 kernel that I installed earlier from within the SlicerJupyter module. Then I put in a few lines of code that makes a box.

If the last line of the cell happens to be of type `<class 'MRMLCorePython.vtkMRMLModelNode'>`, then the output will be shown rendered in the notebook. 

That's cool, but the managed Slicer instance runs into a major crisis. The problem is shown below, where I've defined a box. The box is shown alright in the notebook, but a black rectangle is scraped out of the window of the Slicer instance, which then generally refuse to work: nothing in that window is redrawn correctly afterwards.  Example of kernel file is also enclosed. The Linux console output is:

```
Warning: In /work/Stable/Slicer-0/Libs/MRML/Core/vtkMRMLDisplayNode.cxx, line 831
vtkMRMLModelDisplayNode (0x43e88a0): SetSliceIntersectionVisibility method is deprecated, please use SetVisibility2D instead
```
Before that, I see after restarting:

[I 13:02:25.720 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel a45bc8c0-9fa5-40fc-8c1b-37f4b20c1bb1 restarted
Switch to module:  "Welcome"
Loading Slicer RC file [/home/fusentasticus/.slicerrc.py]
Jupyter connection file: [/home/fusentasticus/.local/share/jupyter/runtime/kernel-a45bc8c0-9fa5-40fc-8c1b-37f4b20c1bb1.json]
Starting Jupyter kernel server
Run with XEUS 0.24.1

The Slicer version is 4.11.20200930 (new release), running on Ubuntu 20.04.

![image](https://user-images.githubusercontent.com/11786553/97901935-d5df6d00-1d0a-11eb-9d76-0af58e7a51b9.png)
```
{
  "shell_port": 57603,
  "iopub_port": 53115,
  "stdin_port": 41961,
  "control_port": 34089,
  "hb_port": 60745,
  "ip": "127.0.0.1",
  "key": "703c2a32-e40336538922c79555486e35",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": "slicer-4.11"
}
```

**Comment by lassoan** [comment]
Thank you for reporting. This automatic off-screen rendering of a model node is an experimental feature, to see if people find it useful, but it is really not essential and off-screen rendering is often problematic (if it does not work for you then you might need to change your driver or configuration settings).

We've recently changed the display function so that when a model node is returned the rendering does not happen automatically but you need to call `slicernb.displayable(modelNode)`.
