### ISSUE TITLE
Vscode Jupyter Server 

### ISSUE THREAD

**Issue by gregspangenberg** [Slicer/SlicerJupyter#55]
Hi, 
I was hoping to use Vscode as it had support for Jupyter notebooks. I have been unable to get it to place nicely however and the kernel is recognized but refuses to start. 

![image](https://user-images.githubusercontent.com/69650301/107170737-1fd19200-698f-11eb-9ada-ee91417f40ca.png)
_kernel recognized_

![image](https://user-images.githubusercontent.com/69650301/107170784-32e46200-698f-11eb-92cd-2e5b5b58b5ca.png)
_kernel selected_

![image](https://user-images.githubusercontent.com/69650301/107170840-53acb780-698f-11eb-9971-9fa8e6f3500a.png)
_attempt to switch to slicer kernel but fails silently_

The kernel starts correctly when connecting to the browser based jupyter notebooks.  Would you have any suggestions as to what i would need to modify to get Vscode to start the kernel?

Thanks for creating this wonderful extension!

**Comment by lassoan** [comment]
The Slicer Jupyter kernel worked for me in VS code a few months ago, but not anymore. When I executed a cell in the notebook I got an error message that the `connection_file` was not found in the argument list in kernel.json, which was clearly wrong. After adding a dummy `connection_file` argument, it complained that it expects the kernel arguments to be exactly a certain format (something like `python-executable -m modulename arg1 arg2...`), which is nonsense (the server should not dictate a specific format for how to call the kernel executable). I've also tried "Existing" Jupyter server options in VS Code GUI and when I copied the server address there and hit Enter, nothing happened. There may be things around the Slicer kernel that work slightly differently than a regular Python kernel, but it looks like notebook support in VS code is broken or at least really fragile.

I've added this line to the slicer startup file (`C:\Users\andra\.slicerrc.py`) to print what VS code does:

    print("arguments="+repr(slicer.app.arguments()))

And I got this in the application log:

    [INFO][Stream] 08.02.2021 18:50:22 [] (unknown:0) - arguments=(
      'C:\\Users\\andra\\AppData\\Local\\NA-MIC\\Slicer 4.13.0-2021-02-04\\bin\\SlicerApp-real.exe',
      'c:\\Users\\andra\\.vscode\\extensions\\ms-python.python-2021.1.502429796\\pythonFiles\\pyvsc-run-isolated.py',
      'c:\\Users\\andra\\.vscode\\extensions\\ms-python.python-2021.1.502429796\\pythonFiles\\interpreterInfo.py')

So, it seems that VS code wants to retrieve information about the interpreter with some custom script, which is totally arbitrary. VS code imposes restrictions and makes assumptions that may be OK for a plain Python kernel using Python or conda distribution but totally inappropriate for custom kernel implementations.

You can try to go back to an earlier Python/Jupyter extension version in VS code or wait for a newer version that has better interoperability.

**Comment by gregspangenberg** [comment]
Thanks for looking into this I appreciate it! I will rollback to an earlier Jupyter extension or simply use the web based jupyter if that doesn't work.

**Comment by lassoan** [comment]
OK! Let us know if rollback works.

**Comment by lassoan** [comment]
VS Code still cannot start the server in Slicer's virtual Python environment but if the server is started from Slicer then VS Code can connect to the running server:

- Start Slicer, go to JupyterKernel module, click Start Jupyter server
- Get the Jupyter server URL from the Slicer application log (it should be something like `http://localhost:8888/lab?token=afc2a22bbe61149ae7c2e831645e5b28384203eb3c3c2da5`), copy to the clipboard
- In Visual Studio code, open a notebook, click in the lower-right corner on "Jupyter server: ..." then select at the list at the top center "Pick how to connect to jupyter" -> "Existing", paste the server URL from the clipboard and hit Enter
- If in the top-right corner the kernel is not "Slicer 4.13" then click there and choose "Slicer 4.13" from the list that appears in the top center

**Comment by lassoan** [comment]
I've made some [fixes](https://github.com/Slicer/SlicerJupyter/commit/b282a2c819da1e3e4fe1ab6c419e2299f976720d) to improve compatibility when using SlicerJupyter as a local server. How to make local server work:
- select PythonSlicer as Python interpreter
- choose Slicer-4.13 as kernel

It seems that the kernel does not show up if the language in kernel.json is set to "python" and changing it to anything else (for example "pythonX") makes it appear.

It may also be necessary to install the kernelspec in the PythonSlicer requirement, replacing `--user` by `--sys-prefix`.

Overall, VSCode Jupyter extension seems to struggle with all but the most basic Jupyter configurations. There are dozens of open issues and support for custom kernels, such as XEUS (that Slicer uses) is quite low on the priority list.
