### ISSUE TITLE
Missing SlicerJupyter 

### ISSUE THREAD

**Issue by dalbenzioG** [Slicer/SlicerJupyter#57]
Hello,
I would like to use SlicerJupyter for a project, but I can't install the latest version.
I am using Ubuntu 20.04 and Slicer-4.11.20210226. I have tried both ways for downloading the extension:
1. Extension Manager - I got the following error *No extensions found for linux:64-bit, revision: '29738'. Please try a different combination*
2. Manually - I followed this link https://www.slicer.org/wiki/Documentation/Nightly/SlicerApplication/ExtensionsManager#How_to_manually_download_an_extension_package.3F and *No extensions found message* was displayed.

I am only able to install SlicerJupyter on Slicer revision = 27567, which is too old for me.
What am I doing wrong? Could you help me, please?
Do you have SliceJupyter for Linux Slicer-4.11.20210226?

Many thanks for considering my request.

**Comment by jamesobutler** [comment]
The current state of SlicerJupyter is described at https://discourse.slicer.org/t/slicer-jupyter-in-slicer-4-11-20210226-linux/16578. 

@lassoan It is currently broken across all platforms for the Slicer preview build. Slicer-4.11.20210226 only has SlicerJupyter available on Windows and macOS currently.

**Comment by dalbenzioG** [comment]
> The current state of SlicerJupyter is described at https://discourse.slicer.org/t/slicer-jupyter-in-slicer-4-11-20210226-linux/16578.
> 
> @lassoan It is currently broken across all platforms for the Slicer preview build. Slicer-4.11.20210226 only has SlicerJupyter available on Windows and macOS currently.

**Comment by dalbenzioG** [comment]
Thank you for your reply, @jamesobutler. I will follow the state of SlicerJupyter on the Slicer Forum. 
Let me know if I could be helpful.

**Comment by jamesobutler** [comment]
To followup SlicerJupyter is available on Windows and macOS at the moment, but has build errors on Linux for both Slicer Stable and Slicer Preview.
