### ISSUE TITLE
Linux: extension SlicerJupyter not available in 4.13 preview releases

### ISSUE THREAD

**Issue by NilsKlarlund** [Slicer/SlicerJupyter#59]
I'm eager to try out new stuff in 4.13 - meanwhile SlicerJupyter has become indispensable. Hope you get a chance to look into the compilation issues on Linux I suspect are at fault because the extension doesn't show up in the extensions manager anymore.
thanks

**Comment by lassoan** [comment]
@jcfr @sjh26 Do you have any idea why the extension fails to build with this error on the factory?

https://slicer.cdash.org/viewBuildError.php?buildid=2388789

```
-- Generating done
-- Build files have been written to: /.../SlicerJupyter-build/xeus-build
[ 76%] Performing build step for 'xeus'
Scanning dependencies of target xeus-static
[  1%] Building CXX object CMakeFiles/xeus-static.dir/src/xauthentication.cpp.o
[  3%] Building CXX object CMakeFiles/xeus-static.dir/src/xcomm.cpp.o
[  4%] Building CXX object CMakeFiles/xeus-static.dir/src/xcontrol.cpp.o
[  6%] Building CXX object CMakeFiles/xeus-static.dir/src/xcontrol_messenger.cpp.o
[  7%] Building CXX object CMakeFiles/xeus-static.dir/src/xdap_tcp_client.cpp.o
/.../SlicerJupyter-build/xeus/src/xdap_tcp_client.cpp: In member function ‘void xeus::xdap_tcp_client::init_tcp_socket(const string&)’:
xeus/src/xdap_tcp_client.cpp:192:44: error: no matching function for call to ‘zmq::message_t::message_t(std::string&)’
             m_socket_id = zmq::message_t(id);
                                            ^
In file included from cppzmq/zmq_addon.hpp:27:0,
                 from xeus/src/xdap_tcp_client.cpp:1:
```

I've built Slicer and SlicerJupyter on Ubuntu 20.04 with default settings without any issues.

**Comment by lassoan** [comment]
Is some very old compiler used on the factory?
How could I reproduce the error on my system so that I can reproduce and (hopefully) fix the error?

**Comment by jcfr** [comment]
> Is some very old compiler used on the factory?

We use a centos7 based environment like the one  used to build official python package.

It uses gcc5 provided by centos7-devtoolset4 by building on top of [dockbuild/centos7-devtoolset4-gcc5](https://github.com/dockbuild/dockbuild/tree/master/centos7-devtoolset4-gcc5). See [here](https://github.com/Slicer/SlicerBuildEnvironment/blob/4663be0ee61196d7d7783c000f0c0bcea7c06030/Docker/qt5-centos7/Dockerfile#L1)

For reference, @sjh26 has been working on updating this and we now have a new dockbuild based image including gcc7, see [dockbuild/centos7-devtoolset7-gcc7](https://github.com/dockbuild/dockbuild/tree/master/centos7-devtoolset7-gcc7)

>  How could I reproduce the error on my system so that I can reproduce and (hopefully) fix the error?

See https://github.com/Slicer/SlicerBuildEnvironment#tutorials

Except you should download the `slicer/buildenv-qt5-centos7:latest` docker image

**Comment by jcfr** [comment]
After ssh'ing into the build machine, here are more details:

```
loading initial cache file /work/Preview/S-0-E-b/SlicerJupyter-build/xeus-prefix/tmp/xeus-cache-Release.cmake
-- xeus version: v0.25.3
-- xeus binary version: v1.0.0
-- CMAKE_CXX_FLAGS:    
-- CMAKE_CXX_FLAGS:    
-- tests disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /work/Preview/S-0-E-b/SlicerJupyter-build/xeus-build
[ 62%] Performing build step for 'xeus'
[  1%] Building CXX object CMakeFiles/xeus-static.dir/src/xdap_tcp_client.cpp.o
/work/Preview/S-0-E-b/SlicerJupyter-build/xeus/src/xdap_tcp_client.cpp: In member function ‘void xeus::xdap_tcp_client::init_tcp_socket(const string&)’:
/work/Preview/S-0-E-b/SlicerJupyter-build/xeus/src/xdap_tcp_client.cpp:192:44: error: no matching function for call to ‘zmq::message_t::message_t(std::string&)’
             m_socket_id = zmq::message_t(id);
                                            ^
In file included from /work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq_addon.hpp:27:0,
                 from /work/Preview/S-0-E-b/SlicerJupyter-build/xeus/src/xdap_tcp_client.cpp:1:
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:391:5: note: candidate: zmq::message_t::message_t(zmq::message_t&&)
     message_t(message_t &&rhs) ZMQ_NOTHROW : msg(rhs.msg)
     ^
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:391:5: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘zmq::message_t&&’
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:371:5: note: candidate: zmq::message_t::message_t(void*, size_t, void (*)(void*, void*), void*)
     message_t(void *data_, size_t size_, free_fn *ffn_, void *hint_ = ZMQ_NULLPTR)
     ^
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:371:5: note:   candidate expects 4 arguments, 1 provided
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:363:5: note: candidate: zmq::message_t::message_t(const void*, size_t)
     message_t(const void *data_, size_t size_)
     ^
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:363:5: note:   candidate expects 2 arguments, 1 provided
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:350:33: note: candidate: template<class ForwardIter> zmq::message_t::message_t(ForwardIter, ForwardIter)
     template<class ForwardIter> message_t(ForwardIter first, ForwardIter last)
                                 ^
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:350:33: note:   template argument deduction/substitution failed:
/work/Preview/S-0-E-b/SlicerJupyter-build/xeus/src/xdap_tcp_client.cpp:192:44: note:   candidate expects 2 arguments, 1 provided
             m_socket_id = zmq::message_t(id);
                                            ^
In file included from /work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq_addon.hpp:27:0,
                 from /work/Preview/S-0-E-b/SlicerJupyter-build/xeus/src/xdap_tcp_client.cpp:1:
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:343:14: note: candidate: zmq::message_t::message_t(size_t)
     explicit message_t(size_t size_)
              ^
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:343:14: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘size_t {aka long unsigned int}’
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:337:5: note: candidate: zmq::message_t::message_t()
     message_t() ZMQ_NOTHROW
     ^
/work/Preview/S-0-E-b/SlicerJupyter-build/cppzmq/zmq.hpp:337:5: note:   candidate expects 0 arguments, 1 provided
make[5]: *** [CMakeFiles/xeus-static.dir/src/xdap_tcp_client.cpp.o] Error 1
```

Happy to try suggestions

**Comment by lassoan** [comment]
This could probably fixed by either going back to some earlier xeus version, or update the compiler. If @sjh26 can test the build on the new image and it works then that would be much preferable.

**Comment by jamesobutler** [comment]
For reference in terms of picking a newer GCC version, Qt6 is using GCC9 as the compiler for most linux distros https://doc-snapshots.qt.io/qt6-dev/supported-platforms.html in addition to minimum usage of C++17 rather than C++11 in Qt5. 

GCC9 was released May 2019 and was the first to mark full support for C++17 which is probably why Qt6 chose it.

^Something to consider if updating GCC on factory

**Comment by lassoan** [comment]
In the meantime, here is a SlicerJupyter installation package (SlicerJupyter-gitb3fba2d-2021-03-21) for Linux for latest Slicer Preview Release (Slicer-4.13.0-2021-10-06) c:\Users\andra\Downloads\30304-linux-amd64-SlicerJupyter-gitb3fba2d-2021-03-21.tar.gz) for testing:

[30304-linux-amd64-SlicerJupyter-gitb3fba2d-2021-03-21.tar.gz](https://github.com/Slicer/SlicerJupyter/files/7305919/30304-linux-amd64-SlicerJupyter-gitb3fba2d-2021-03-21.tar.gz)
