### ISSUE TITLE
Help me! Update plane from fiducial points...How can I  aligne the red plane with Coordinate axis? 

### ISSUE THREAD

**Issue by jumbojing** [Slicer/SlicerJupyter#61]
```python
# Update plane from fiducial points
def UpdateSlicePlane(data):
  a = data
  points = np.array([list(zip(*a))])[0]
#     b2 = np.array([list(zip(*a))])
  sliceNode = slicer.app.layoutManager().sliceWidget("Red").mrmlSliceNode()
  planePosition = points.mean(axis=1)
  planeNormal = np.cross(points[:,1] - points[:,0], points[:,2] - points[:,0])
  planeX = points[:,1] - points[:,0]
  sliceNode.SetSliceToRASByNTP(planeNormal[0], planeNormal[1], planeNormal[2],
    planeX[0], planeX[1], planeX[2],
    planePosition[0], planePosition[1], planePosition[2], 0)

UpdateSlicePlane(data33)
slicernb.ViewDisplay('OneUpRedSlice', center=False)
```

![下载](https://user-images.githubusercontent.com/10215735/116176690-26c5a080-a745-11eb-8c75-e25a6f955804.png)

我想将图片对齐,就像这样:

 I  want aligne the red plane with Coordinate axis?, like that:

![image](https://user-images.githubusercontent.com/10215735/116177287-1eba3080-a746-11eb-960b-a55bbfcaf8a6.png)

**Comment by lassoan** [comment]
See this example for a solution: https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#set-slice-position-and-orientation-from-a-normal-vector-and-position
