### ISSUE TITLE
Kernel misses autoreload IPython extension

### ISSUE THREAD

**Issue by SchraivogelS** [Slicer/SlicerJupyter#62]
Hi there,
first of all thanks for the jupyter notebook extension for 3DSlicer.
It allows for streamlined data processing and reproducible workflows.

Slicer kernel seems to miss autoreload extension, which is a handy feature within jupyter notebooks.

`%load_ext autoreload`
causes AttributeError: 'kernel.XInteractiveShell' object has no attribute 'events'

**Comment by lassoan** [comment]
We use xeus-python kernel, which might have not implemented this yet - see the discussion here:

https://github.com/jupyter-xeus/xeus-python/issues/63#issuecomment-722936452

Could you ask for clarification either in that issue or creating a new one and report here what you find out?

If it is fixed/implemented recently then we may just need to update the xeus-python kernel version in SlicerJupyter.

**Comment by SchraivogelS** [comment]
They added a bunch of magics at the beginning of this year:
[https://github.com/jupyter-xeus/xeus-python/blob/fc09e25d882e62bf72cc3ae6644b29cadd174fb8/notebooks/xeus-magics.ipynb](url)

Just installed xeus-python 0.12.5 in a fresh conda env along with python 3.9.6 and autoreload extension is available.
Is an update feasible?

**Comment by lassoan** [comment]
I've tried to update but recent xeus-python versions require IPython>=7.21, but the last IPython version for Python-3.6 is IPython-7.15. We need to wait until Slicer core is updated to at least Python-3.7 - see https://github.com/Slicer/Slicer/issues/5014.

**Comment by SchraivogelS** [comment]
Ok, thanks for checking.

Am 09.07.2021 um 03:48 schrieb Andras Lasso ***@***.***>:

﻿

I've tried to update but recent xeus-python versions require IPython>=7.21, but the last IPython version for Python-3.6 is IPython-7.15. We need to wait until Slicer core is updated to at least Python-3.7 - see Slicer/Slicer#5014<https://github.com/Slicer/Slicer/issues/5014>.

**Comment by lassoan** [comment]
We have updated Slicer's Python some time ago and can use the latest xeus-python, so hopefully the problem is now fixed.
