### ISSUE TITLE
SlicerJupyter not found in 3DSlicer Extension Manager

### ISSUE THREAD

**Issue by quarkstar-codes** [Slicer/SlicerJupyter#63]
Hello! I'm new to 3D Slicer and am looking to integrate it into my jupyter notebooks, I've installed 3D slicer but can't locate SlicerJupyter in the Extension Manager.

**Comment by jamesobutler** [comment]
What platform are you using? SlicerJupyter has been unavailable on Linux as tracked in issue #59.

If on Windows or macOS, which version of Slicer are you using? Slicer 4.13.20210919 would be the latest Slicer preview version.
