### ISSUE TITLE
SlicerKernel and getpass.getpass() echoing to the notebook.

### ISSUE THREAD

**Issue by lostintheunderflow** [Slicer/SlicerJupyter#65]
Running under the slicer kernel getpass echos to the notebook and I think it is caused by this issue:
https://github.com/jupyter-xeus/xeus-python/issues/325

That issue says that it is solved in the latest  xeus-python.

Is it possible to upgrade the version of xeus?

**Comment by lassoan** [comment]
We have upgraded xeus-python, hopefully this fixed the issue.
